version: "3.3"
services:
  visualizer_client:
    image: warpenguin.no-ip.org/warpvisualizerhelper:latest
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      mode: global
      placement:
        constraints: [node.labels.master != true]
    networks:
      - host

  visualizer:
    image: warpenguin.no-ip.org/warpvisualizer:latest
    ports:
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      placement:
        constraints: 
          - node.role == manager
          - node.labels.master == true

networks:
  host:
    external:
       name: "host"
